const fs = require('fs');
const path = require('path');

const backendUrl = (process.env.BACKEND_URL || 'http://localhost:4000').replace(/\/$/, '');
const wsUrl = backendUrl.startsWith('https://')
  ? backendUrl.replace('https://', 'wss://')
  : backendUrl.replace('http://', 'ws://');

// HTTP uses the Vercel API function (/api/graphql) which proxies to Railway server-to-server.
// WebSocket must be an absolute URL pointing directly at Railway.
const content = `// Generated by scripts/set-env.js at build time — do not edit manually
export const environment = {
  production: true,
  backendHttpUrl: '/api/graphql',
  backendWsUrl: '${wsUrl}/graphql'
};
`;

const dest = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(dest, content, 'utf8');
console.log(`✅ environment.prod.ts generated — WS: ${wsUrl}/graphql`);
