// Generated by scripts/set-env.js at build time — do not edit manually
export const environment = {
  production: true,
  backendHttpUrl: '/api/graphql',
  backendWsUrl: 'wss://growwatch-production.up.railway.app/graphql'
};
