// Generated by scripts/set-env.js at build time — do not edit manually
export const environment = {
  production: true,
  backendHttpUrl: 'https://your-backend.railway.app/graphql',
  backendWsUrl: 'wss://your-backend.railway.app/graphql'
};
